CREATE DATABASE dbRoles;

use dbRoles;

CREATE TABLE ROLES(
	IDROL VARCHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    CONTRASEÑA VARCHAR(50) NOT NULL
    );
    
    
INSERT INTO ROLES VALUES("E01", "NIDAE", "MUBARAK135k=");
INSERT INTO ROLES VALUES("C01", "FERMIN", "VANDALxYsh!");
INSERT INTO ROLES VALUES("E02", "AARON", "PLANETSIDE446g!");

    